language: node_js
node_js: 8
before_script: 
  - cd web
  - echo "Installing Node Modules"
  - npm install
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  message: "Deploying to Firebase..."
  token: 
    secure: "SRYIP4AUfz9+dbnEHtEyerfOnyJHFIqfTMaMl+7p9oDkJmEQ/JhfBEcrUGh3ssdxrvFcIwIbegvY2HiCmYBRF6N6KJJ8LV/utocBUmgteCUh6g3bft3c0iQRSIVjqfiZnWmOZdafB4Ptc1kini/nAEqf2zmoh6o0/pZaU3szyyUj0YWiOpG/i7/Cv4mW57LLNkhDcQvvuRyjttPeMnfZaXwOlbLtsopbuA7CG/bADlK3rNE4EDO8SiBYQVf4vQzXwSwZzcCrjutZmeEYf/IzoWBKcD4Jv/whdS0MW1XUPZSYemnXDKSqUg+z4rj8ny675p/Zrlk74xBVpas06kIoKgvsrhqAL1KfTVzprppVSe9aaRTFp3DkVUJgxsz48o7cBw6b0ol4YpS+LXAnoTOvOz3VfC8jpLMSJDwbqJjBCBCZxH1czXo9WQ/3xLbcCIkgO5ouv9GkvyEs5YUuNCCGBBnguoUpUkE9twNIP8GlBExY87cV+YdwKQKwo9k+s2Wp3fBnuZp1JCW4JUY2KTdJmIPODK1ZI1e2vp7KpAI6iRufFkTy7ajelgs3/M6Z5bae5V8VeCyhCzosYGsP/QdDc5NJdQYJc/n4TwmyMqzEY8LQLNbooEqaoUNM0vO+K1C2zSW1Qu01hxMbYkS5pBX7XsddwqWDcYSKp18MRohfZgQ="
  project: "production"
after_script: echo "Successfully Deployed"