language: node_js
node_js: 8
before_script:
- cd web
- echo "Installing Node Modules"
- npm install
script: npm run build
deploy:
  provider: firebase
  skip_cleanup: true
  message: Deploying to Firebase...
  token:
    secure: o8c6eaI8BVuBkh4lx83TfA7rejopdr9FMA1xhfSXx6sP3hmvcmM5KpnozVkhUawk4I5Vn7hoTtqP9tQsnxmAVgdNZgqa2SjKPWD1cjER55ido4sdW7JBwxVqiEOuB1DnmhHIOxiUqlqtBwi6Kkrx4lIhVshedppnvwq3/5VNJ4xvldxGhCz20keDdVm2s9RKoSSucAqm1gYiMWid/0bD9hf+BwXCH9DRBIessSQpHYXianQr2ubm6Ng/Htdt0djGnt152+jxFy0XFbTER+axXncN/LSok1NrSNMNqC6u0+5+yAwg+IdE+Pbl2udgQ9efuZWz+UOfMn94gwgBYr6tGR8gh6TcySw+uv2DkbrzzCV5UU8AQWCyqgsoTQdojrBJuGGfM7KElCZe6YQSSEjsvEVpAGm6qI+9iBi0OE/W/zVWAQUFSxp52zpqDmVY+vtS9s9tqSBTR6RLl+Mjcd0Ptb17LyE63pVMMnWnhbjHFLsGTWlXgSvA4plhD9EfBYvy4jUPAeJeTlT9zr7edDA5BdryoV49h4tKPH5oJpihr6wGAgjVIpaEyZCye+h50lBJnDf9TZ/PTbAHTZGGor5WnDR1u9aIExv2yvFYx2204PPhs9TmWuZ9IlfWLmeoP8VWQDMhVotZ2pNfr/ed6kXRcr6jpvpGkBSFbJW2thvKNLk=
  project: "production"
after_script: echo "Successfully Deployed"
env:
  global:
    secure: o8c6eaI8BVuBkh4lx83TfA7rejopdr9FMA1xhfSXx6sP3hmvcmM5KpnozVkhUawk4I5Vn7hoTtqP9tQsnxmAVgdNZgqa2SjKPWD1cjER55ido4sdW7JBwxVqiEOuB1DnmhHIOxiUqlqtBwi6Kkrx4lIhVshedppnvwq3/5VNJ4xvldxGhCz20keDdVm2s9RKoSSucAqm1gYiMWid/0bD9hf+BwXCH9DRBIessSQpHYXianQr2ubm6Ng/Htdt0djGnt152+jxFy0XFbTER+axXncN/LSok1NrSNMNqC6u0+5+yAwg+IdE+Pbl2udgQ9efuZWz+UOfMn94gwgBYr6tGR8gh6TcySw+uv2DkbrzzCV5UU8AQWCyqgsoTQdojrBJuGGfM7KElCZe6YQSSEjsvEVpAGm6qI+9iBi0OE/W/zVWAQUFSxp52zpqDmVY+vtS9s9tqSBTR6RLl+Mjcd0Ptb17LyE63pVMMnWnhbjHFLsGTWlXgSvA4plhD9EfBYvy4jUPAeJeTlT9zr7edDA5BdryoV49h4tKPH5oJpihr6wGAgjVIpaEyZCye+h50lBJnDf9TZ/PTbAHTZGGor5WnDR1u9aIExv2yvFYx2204PPhs9TmWuZ9IlfWLmeoP8VWQDMhVotZ2pNfr/ed6kXRcr6jpvpGkBSFbJW2thvKNLk=
